name: Generate C code and Export DBC to Excel

on:
  push:
    branches:
      - master

jobs:
  generate_and_export:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cantools openpyxl

      - name: Generate C code for all DBC files
        run: |
          mkdir -p generated
          find . -type f -name "*.dbc" | while read -r dbcfile; do
            base=$(basename "$dbcfile" .dbc)
            outdir="generated/$base"
            mkdir -p "$outdir"
            echo "Generating C code for $dbcfile into $outdir"
            cantools generate_c_source "$dbcfile" --output "$outdir"
          done

      - name: Run export script to Excel
        run: python export_dbc_to_excel.py

      - name: Commit and push generated files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Pull latest changes and rebase to avoid push conflicts
          git pull --rebase origin master

          git add generated/ dbc_signals.xlsx
          git diff --cached --quiet || git commit -m "Auto-generated C code and Excel from DBC files"
          git push origin master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
