name: Generate C code and Export DBC to Excel

on:
  push:
    branches:
      - master

jobs:
  generate_and_export:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

- name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Install latest version of cantools
          pip install --upgrade cantools openpyxl
          
          # Check version and available commands
          cantools --help
          cantools --version

      - name: Generate C code for all DBC files
        run: |
          mkdir -p generated
          find . -type f -name "*.dbc" | while read -r dbcfile; do
            base=$(basename "$dbcfile" .dbc)
            outdir="generated/$base"
            mkdir -p "$outdir"
            echo "Generating C code for $dbcfile into $outdir"
            # FIXED: Use generate_c_code instead of generate_c_source
            cantools generate_c_code "$dbcfile" --output-directory "$outdir"
            
            # Also generate with verbose output to see what's created
            echo "Generated files in $outdir:"
            ls -la "$outdir"
          done

      - name: Export DBC to Excel
        run: python export_dbc_to_excel.py

      - name: Commit and push generated files if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add generated/ dbc_signals.xlsx

          if ! git diff --cached --quiet; then
            git commit -m "Auto-generated C code and Excel export from DBC files"
          fi

          git reset --hard
          git clean -fd
          git pull --rebase
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          
