name: Generate C code from all DBC files

on:
  push:
    branches:
      - master

jobs:
  generate_c_from_dbc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install cantools
        run: |
          pip install cantools

      - name: Generate C code for all DBC files
        run: |
          mkdir -p generated
          # find all .dbc files, loop over them
          find . -type f -name "*.dbc" | while read -r dbcfile; do
            # get basename without extension
            base=$(basename "$dbcfile" .dbc)
            outdir="generated/$base"
            mkdir -p "$outdir"
            echo "Generating C code for $dbcfile into $outdir"
            cantools generate_c_source "$dbcfile" --output "$outdir"
          done

      - name: Commit generated files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add generated/
          git diff --cached --quiet || git commit -m "Auto-generated C code from DBC files"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
