name: Export DBC to Excel and Commit

on:
  push:
    branches:
      - main

jobs:
  export_excel:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cantools openpyxl

      - name: Run export script
        run: python export_dbc_to_excel.py

      - name: Commit and push generated Excel file if changed
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add dbc_signals.xlsx
          # Commit only if there are changes
          git diff --quiet && git diff --staged --quiet || git commit -m "Update generated Excel file"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
